-- LastTime production storage. IDs are generated by the durable agent so the
-- same records can move safely between local development and Supabase.

create table if not exists public.workflows (
  id text primary key,
  owner_key text not null,
  name text not null check (char_length(name) between 1 and 120),
  goal text not null,
  trigger text not null,
  steps jsonb not null default '[]'::jsonb check (jsonb_typeof(steps) = 'array'),
  required_connections jsonb not null default '[]'::jsonb check (jsonb_typeof(required_connections) = 'array'),
  success_criteria jsonb not null default '[]'::jsonb check (jsonb_typeof(success_criteria) = 'array'),
  status text not null default 'draft' check (status in ('draft', 'ready', 'paused', 'archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.workflow_runs (
  id text primary key,
  workflow_id text not null references public.workflows(id) on delete cascade,
  owner_key text not null,
  status text not null check (status in ('queued', 'running', 'waiting_for_approval', 'completed', 'failed', 'blocked')),
  input jsonb not null default '{}'::jsonb check (jsonb_typeof(input) = 'object'),
  agent37_session_id text,
  output jsonb check (output is null or jsonb_typeof(output) = 'object'),
  error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.workflow_events (
  id text primary key,
  run_id text not null references public.workflow_runs(id) on delete cascade,
  owner_key text not null,
  sequence integer not null check (sequence > 0),
  type text not null,
  data jsonb not null default '{}'::jsonb check (jsonb_typeof(data) = 'object'),
  created_at timestamptz not null default now(),
  unique (run_id, sequence)
);

create table if not exists public.integration_receipts (
  id text primary key,
  owner_key text not null default 'system',
  provider text not null check (provider in ('agent37', 'monid', 'openai', 'supabase', 'instacloud')),
  external_id text,
  kind text not null,
  status text not null,
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz not null default now()
);

create index if not exists workflows_owner_updated_idx
  on public.workflows (owner_key, updated_at desc);
create index if not exists workflow_runs_owner_updated_idx
  on public.workflow_runs (owner_key, updated_at desc);
create index if not exists workflow_runs_workflow_updated_idx
  on public.workflow_runs (workflow_id, updated_at desc);
create index if not exists workflow_events_owner_created_idx
  on public.workflow_events (owner_key, created_at desc);
create index if not exists workflow_events_run_sequence_idx
  on public.workflow_events (run_id, sequence);
create index if not exists integration_receipts_provider_created_idx
  on public.integration_receipts (provider, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists workflows_set_updated_at on public.workflows;
create trigger workflows_set_updated_at
before update on public.workflows
for each row execute function public.set_updated_at();

drop trigger if exists workflow_runs_set_updated_at on public.workflow_runs;
create trigger workflow_runs_set_updated_at
before update on public.workflow_runs
for each row execute function public.set_updated_at();

alter table public.workflows enable row level security;
alter table public.workflow_runs enable row level security;
alter table public.workflow_events enable row level security;
alter table public.integration_receipts enable row level security;

revoke all on public.workflows from anon;
revoke all on public.workflow_runs from anon;
revoke all on public.workflow_events from anon;
revoke all on public.integration_receipts from anon, authenticated;

grant select, insert, update, delete on public.workflows to authenticated, service_role;
grant select, insert, update, delete on public.workflow_runs to authenticated, service_role;
grant select, insert, update, delete on public.workflow_events to authenticated, service_role;
grant select, insert, update, delete on public.integration_receipts to service_role;

drop policy if exists workflows_owner_policy on public.workflows;
create policy workflows_owner_policy on public.workflows
  for all to authenticated
  using (owner_key = (select auth.uid())::text)
  with check (owner_key = (select auth.uid())::text);

drop policy if exists workflow_runs_owner_policy on public.workflow_runs;
create policy workflow_runs_owner_policy on public.workflow_runs
  for all to authenticated
  using (owner_key = (select auth.uid())::text)
  with check (owner_key = (select auth.uid())::text);

drop policy if exists workflow_events_owner_policy on public.workflow_events;
create policy workflow_events_owner_policy on public.workflow_events
  for all to authenticated
  using (owner_key = (select auth.uid())::text)
  with check (owner_key = (select auth.uid())::text);
