import { randomUUID } from "node:crypto";
import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import type { RunStatus, StoreData, Workflow, WorkflowEvent, WorkflowRun } from "./types";

const localPath=process.env.LASTTIME_DATA_FILE||join(process.cwd(),".data","lasttime.json");
const emptyStore=():StoreData=>({workflows:[],runs:[],events:[]});
function hasSupabase(){return Boolean(process.env.SUPABASE_URL&&process.env.SUPABASE_SERVICE_ROLE_KEY)}
async function supabaseRequest<T>(path:string,init:RequestInit={}):Promise<T>{const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("Supabase is not configured");const headers:Record<string,string>={apikey:key,"content-type":"application/json",...(init.headers as Record<string,string>||{})};if(!key.startsWith("sb_secret_"))headers.authorization=`Bearer ${key}`;const response=await fetch(`${url.replace(/\/$/,"")}/rest/v1/${path}`,{...init,headers});if(!response.ok)throw new Error(`Supabase ${response.status}: ${await response.text()}`);if(response.status===204)return undefined as T;return response.json() as Promise<T>}
async function readLocal():Promise<StoreData>{try{return JSON.parse(await readFile(localPath,"utf8")) as StoreData}catch(error){if((error as NodeJS.ErrnoException).code==="ENOENT")return emptyStore();throw error}}
async function writeLocal(data:StoreData){await mkdir(dirname(localPath),{recursive:true});const temporary=`${localPath}.${randomUUID()}.tmp`;await writeFile(temporary,JSON.stringify(data,null,2),"utf8");await rename(temporary,localPath)}
function workflowFromRow(row:Record<string,unknown>):Workflow{return{id:String(row.id),ownerKey:String(row.owner_key),name:String(row.name),goal:String(row.goal),trigger:String(row.trigger),steps:row.steps as Workflow["steps"],requiredConnections:row.required_connections as string[],successCriteria:row.success_criteria as string[],status:row.status as Workflow["status"],createdAt:String(row.created_at),updatedAt:String(row.updated_at)}}
function runFromRow(row:Record<string,unknown>):WorkflowRun{return{id:String(row.id),workflowId:String(row.workflow_id),ownerKey:String(row.owner_key),status:row.status as RunStatus,input:row.input as Record<string,unknown>,agent37SessionId:row.agent37_session_id?String(row.agent37_session_id):undefined,output:row.output as Record<string,unknown>|undefined,error:row.error?String(row.error):undefined,createdAt:String(row.created_at),updatedAt:String(row.updated_at)}}
export async function saveWorkflow(workflow:Workflow):Promise<Workflow>{if(hasSupabase()){const rows=await supabaseRequest<Record<string,unknown>[]>("workflows",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({id:workflow.id,owner_key:workflow.ownerKey,name:workflow.name,goal:workflow.goal,trigger:workflow.trigger,steps:workflow.steps,required_connections:workflow.requiredConnections,success_criteria:workflow.successCriteria,status:workflow.status})});return workflowFromRow(rows[0])}const data=await readLocal();data.workflows.push(workflow);await writeLocal(data);return workflow}
export async function listWorkflows(ownerKey:string):Promise<Workflow[]>{if(hasSupabase()){const rows=await supabaseRequest<Record<string,unknown>[]>(`workflows?owner_key=eq.${encodeURIComponent(ownerKey)}&order=updated_at.desc`);return rows.map(workflowFromRow)}return(await readLocal()).workflows.filter(w=>w.ownerKey===ownerKey).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))}
export async function getWorkflow(ownerKey:string,workflowId:string):Promise<Workflow|undefined>{if(hasSupabase()){const rows=await supabaseRequest<Record<string,unknown>[]>(`workflows?id=eq.${encodeURIComponent(workflowId)}&owner_key=eq.${encodeURIComponent(ownerKey)}&limit=1`);return rows[0]?workflowFromRow(rows[0]):undefined}return(await readLocal()).workflows.find(w=>w.id===workflowId&&w.ownerKey===ownerKey)}
export async function createRun(run:WorkflowRun):Promise<WorkflowRun>{if(hasSupabase()){const rows=await supabaseRequest<Record<string,unknown>[]>("workflow_runs",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({id:run.id,workflow_id:run.workflowId,owner_key:run.ownerKey,status:run.status,input:run.input,agent37_session_id:run.agent37SessionId})});return runFromRow(rows[0])}const data=await readLocal();data.runs.push(run);await writeLocal(data);return run}
export async function updateRun(ownerKey:string,runId:string,patch:Partial<Pick<WorkflowRun,"status"|"agent37SessionId"|"output"|"error">>):Promise<WorkflowRun>{const updatedAt=new Date().toISOString();if(hasSupabase()){const payload:Record<string,unknown>={updated_at:updatedAt};if(patch.status)payload.status=patch.status;if(patch.agent37SessionId!==undefined)payload.agent37_session_id=patch.agent37SessionId;if(patch.output!==undefined)payload.output=patch.output;if(patch.error!==undefined)payload.error=patch.error;const rows=await supabaseRequest<Record<string,unknown>[]>(`workflow_runs?id=eq.${encodeURIComponent(runId)}&owner_key=eq.${encodeURIComponent(ownerKey)}`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify(payload)});if(!rows[0])throw new Error("Run not found");return runFromRow(rows[0])}const data=await readLocal();const run=data.runs.find(r=>r.id===runId&&r.ownerKey===ownerKey);if(!run)throw new Error("Run not found");Object.assign(run,patch,{updatedAt});await writeLocal(data);return run}
export async function appendEvent(event:WorkflowEvent):Promise<WorkflowEvent>{if(hasSupabase()){const rows=await supabaseRequest<Record<string,unknown>[]>("workflow_events",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({id:event.id,run_id:event.runId,owner_key:event.ownerKey,sequence:event.sequence,type:event.type,data:event.data})});return{...event,createdAt:String(rows[0].created_at)}}const data=await readLocal();data.events.push(event);await writeLocal(data);return event}
export function storageMode():"supabase"|"local"{return hasSupabase()?"supabase":"local"}
